from setuptools import find_packages, setup


with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="openmanus",
    version="0.1.0",
    author="mannaandpoem and OpenManus Team",
    author_email="mannaandpoem@gmail.com",
    description="A versatile agent that can solve various tasks using multiple tools",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/FoundationAgents/OpenManus",
    packages=find_packages(exclude=["tests", "tests.*"]),
    py_modules=["main", "run_flow", "run_mcp", "sandbox_main"],
    install_requires=[
        "pydantic~=2.10.6",
        "pydantic_core~=2.27.2",
        "openai~=1.66.3",
        "tenacity~=9.0.0",
        "pyyaml~=6.0.2",
        "loguru~=0.7.3",
        "structlog~=25.4.0",
        "numpy",
        "tiktoken~=0.9.0",
        "tomli>=2.0.0",
        "tomli-w~=1.2",
        "html2text~=2024.2.26",
        "pillow~=10.4",
        "unidiff~=0.7.5",
        "browser-use~=0.1.40",
        "googlesearch-python~=1.3.0",
        "baidusearch~=1.0.3",
        "duckduckgo_search~=7.5.3",
        "markdownify>=0.14,<1.2",
        "aiofiles~=24.1.0",
        "colorama~=0.4.6",
        "playwright~=1.56.0",
        "pandas>=2.2",
        "matplotlib>=3.9",
        "openpyxl>=3.1",
        "pypdf>=5.0",
        "python-docx>=1.1",
        "docker~=7.1.0",
        "mcp~=1.5.0",
        "httpx>=0.27.0",
        "boto3~=1.37.0",
        "daytona==0.21.8",
        "requests~=2.32.3",
        "beautifulsoup4~=4.13.3",
        "crawl4ai~=0.6.3",
        "huggingface-hub~=0.29.2",
        "fastapi~=0.115.11",
        "uvicorn[standard]~=0.34.0",
        "sqlalchemy>=2.0",
        "aiosqlite>=0.20",
        "pyjwt>=2.8",
        "bcrypt>=4.2",
        "python-multipart>=0.0.18",
    ],
    extras_require={
        "test": ["pytest~=8.3.5", "pytest-asyncio~=0.25.3", "respx>=0.22"],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.11",
    entry_points={
        "console_scripts": [
            "openmanus=main:cli",
        ],
    },
)
